services:
    mongodb:
        image: mongo:latest
        container_name: mongodb_pruebas
        restart: always
        environment:
            MONGO_INITDB_ROOT_USERNAME: admin
            MONGO_INITDB_ROOT_PASSWORD: password123
            MONGO_INITDB_DATABASE: base_pruebas
        ports:
            - "27017:27017"
        volumes:
            - mongo_data:/data/db

    usuarios-app:
        build: .
        container_name: api-users-app
        ports:
            - "8080:8080"
        environment:
            - SPRING_DATA_MONGODB_URI=mongodb://admin:password123@mongodb:27017/base_pruebas?authSource=admin
        depends_on:
            - mongodb
        restart: always

volumes:
    mongo_data:
