services:
    mongodb:
        image: mongo:latest
        container_name: mongodb_pruebas
        restart: always
        environment:
            MONGO_INITDB_ROOT_USERNAME: admin
            MONGO_INITDB_ROOT_PASSWORD: password123
            MONGO_INITDB_DATABASE: base_pruebas
        ports:
            - "27017:27017"
        volumes:
            - mongo_data:/data/db

volumes:
    mongo_data:
